build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm run pretest && npm run test
            coverage:
              file: coverage/clover.xml
              format: clover